[package]
name = "mafft-types"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Pure Rust types for MAFFT multiple sequence alignment"
readme = "../../README.md"

[dependencies]
num-complex = "0.4"
